### ISSUE TITLE
handleFileUploaded extension from path only works for certain paths

### ISSUE THREAD

**Issue by devland** [otacke/h5p-editor-3d-model-loader#25]
The file upload path extension extraction logic from [here](https://github.com/otacke/h5p-editor-3d-model-loader/blob/d99aad7a56dfc472bc47ff09120ab289f41f253f/src/scripts/h5peditor-3d-model-loader.js#L275) yields an empty string for paths such as `files/ba57ccad04c3eeda2d592b04255150e5.glb` which, in turn, generates the `This file doesn't seem to be a supported 3D model type.` error.
It only works with paths such as `files/file-6750223312a6a.glb#tmp`.
This can be reproduced when uploading a glb file in the editor while running it in the [h5p-cli](https://github.com/h5p/h5p-cli).

**Comment by otacke** [comment]
Why does it work perfectly fine in other H5P integrations such as the plugin for WordPress, Lumi or H5P.com then?

**Comment by otacke** [comment]
Added a generalization in https://github.com/otacke/h5p-editor-3d-model-loader/commit/171a081d43a7d97844103f49882b46e6657f647f to please the H5P-CLI, tool. It's not an issue in regular H5P integrations as mentioned.
